### ISSUE TITLE
XML Olarak indirme

### ISSUE THREAD

**Issue by yazilimciadam** [f/fatura#10]
XML Formatında indirme eklenir mi acaba?  Ben bulamadım yada yöntemi kaçırdım. Eğer ipucu alabilirsem ekleyebilirim.

**Comment by ademalidurmus** [comment]
GIB veriyi zip olarak sunuyor. XML veya HTML olarak ayri dosyalar seklinde inemiyor diye biliyorum. Konuyu bu acidan inceleyip zip dosyasini acarak icinden XML dosyasina erismeniz gerekebilir.

**Comment by yazilimciadam** [comment]
Ben şurdan yola çıktım bazı muhasebe programları direk veriye erişebildiği için onlar kesin olarak XML Olarak erişiyordur diye düşündüm. Dökümantasyonlara baktım bi türlü erişemedim.

**Comment by ademalidurmus** [comment]
Anladim, resmi dokuman erisim baglantisi var mi? Ben resmi herhangi bir dokumana erisimedim de :) Muhasebe yazilimlari sayet hedef url dogrudan GIB degilde kendi servisleri ise; belirttigim yontem ile ilgili dosyayi sunuyor olanbilirler.

**Comment by yazilimciadam** [comment]
Muhasebe uygulamalarından kastım basit bazı uygulamalar bile veri çekebiliyor. Onları anlamıyorum sadece mesela link ekliyim .
https://izsmmmo.org.tr/Haberler/Detay/20200409215600/USTAD-Programi

**Comment by ademalidurmus** [comment]
Anladim bilgiler icin tesekkurler.
