### ISSUE TITLE
Bize kesilen faturalar

### ISSUE THREAD

**Issue by serkandiker** [f/fatura#13]
Fatih bey bize kesilmiş olan faturaları portaldan görebiliyoruz . Bu verileri sayfamıza nasıl çekebiliriz ?? bir yönerge bulunmaktamıdır????

**Comment by demirdev** [comment]
Merhaba @serkandiker yeni bir fonksiyon ekledim. Kabul görürse kullanabilirsin.  #14

**Comment by f** [comment]
Teşekkürler @demirdev
