### ISSUE TITLE
Bir lisans dosyası eklenmeli

### ISSUE THREAD

**Issue by nyucel** [f/fatura#2]
MIT lisansının kullanımını sağlamak için sadece README dosyasına lisansı MIT yazmak yeterli değil. Aşağıdaki adresten görülebileceği gibi "telif hakkı bildirimi ve işbu izin bildirimi yazılımın tüm kopyalarına veya önemli parçalarına eklenmelidir". 

[1] http://ozgurlisanslar.org.tr/mit/

**Comment by f** [comment]
Eklendi. Teşekkürler.
